#!python
file="allherbs"

#file = raw_input("Which inputfile? ")
#if "." in file:
#     file = file[:file.find(".")]

inp = open(file+".knx",'r')
outas = open(file+".asx",'w')
outob = open(file+".obx",'w')

totnumb = 0

for line in inp:
     totnumb = totnumb + 1

inp.seek(0)     
#inp.close()
#inp = open(file+".knx",'r')
#totnumb = 8

number = 0

line = inp.readline()
number = number + 1 
while "Herb" not in line:
     line = inp.readline()
     number = number + 1

while number < totnumb:
     line = inp.readline()
     number = number + 1
     if (line[:5]) == "aster":
#           outas.write(str(line[7:12])+"\n")
            outas.write(line[7:12]+"\n")
     if (line[:5]) == "obeli":
#           outob.write(str(line[7:12])+"\n")
            outob.write(line[7:12]+"\n")

inp.close()
outas.close()
outob.close()
 
