#!python
#import sys
file1=input("Which inputfile? ")

if "." in file1:
     file1 = file1[:file1.find(".")]

try:
     inp= open(file1+".knx",'r')
except:
     print ('File cannot be opened:', file1+".knx")
#     sys.stderr.write('File cannot be opened:')
     exit()

outas = open(file1+".asx",'w')
outob = open(file1+".obx",'w')

totnumb = 0

for line in inp:
     totnumb = totnumb + 1

inp.seek(0)     
#inp.close()
#inp = open(file+".knx",'r')
#totnumb = 8

number = 0

line = inp.readline()
number = number + 1 
while "Herb" not in line:
     line = inp.readline()
     number = number + 1

while number < totnumb:
     line = inp.readline()
     number = number + 1
     spacepos = line.find(' ')
     if (line[:spacepos-1]) == "asterix":
#            outas.write(str(line[spacepos+1:]))
             outas.write(line[spacepos+1:])
     if (line[:spacepos-1]) == "obelix":
#            outob.write(str(line[spacepos+1:]))
             print("Boe", sys.stderr)
#             sys.stdout.write("Boe \n")
#             sys.stderr.write("None \n")
             outob.write(line[spacepos+1:])

inp.close()
outas.close()
outob.close()
 
